HOST: https://victorique-demo.appspot.com/api/
--- Victorique ---

---
[Victorique](https://github.com/kelp404/Victorique) is an error report server on Google App Engine.  
You could download this project and then deploy to GAE with free plan.  
Your app could send error information to Victorique with RESTful API.  
---




--
Logs
--

#Send the log data to server (JSONP).
GET /applications/{application_key}/logs
{
    "title": "log title", // required
    // others arguments are optional
    "user": "name<name@gmail.com>",
    "document": "{\"description\": \"note\"}" // json
}
< 200

#Send the log data to server.
POST /applications/{application_key}/logs
> Content-Type: application/json
{
    "title": "log title", // required
    // others arguments are optional
    "user": "name<name@gmail.com>",
    "document": {
        "description": "note",
        "...": "..."
    }
}
< 200
